### ISSUE TITLE
can you add the subject, action, and place attribute to the dataset?

### ISSUE THREAD

**Issue by nguyentr17** [xyliu-cs/ConflictVIS#1]
Hi,

I'm using your dataset to study the knowledge conflict phenomenon in VLM. For each sample, can you add the subject, action, and place you use to generate the question to the dataset? 

If you have the list of all subjects you use, can you share with me in advance? Thanks!

**Comment by xyliu-cs** [comment]
> Hi,
> 
> 
> 
> I'm using your dataset to study the knowledge conflict phenomenon in VLM. For each sample, can you add the subject, action, and place you use to generate the question to the dataset? 
> 
> 
> 
> If you have the list of all subjects you use, can you share with me in advance? Thanks!

Hi, could you provide your email address?

**Comment by nguyentr17** [comment]
My email is tramnguyen@umass.edu. Thanks!

**Comment by Hyperwjf** [comment]
Hi, 
Thank you for your great work! 
Can you share the subject, action, and place attributes of questions with me?
My email is junfei.wu@cripac.ia.ac.cn. Thanks!

**Comment by xyliu-cs** [comment]
Thank you for your inquiry, I've sent you the relevant data to your email. Please take your time to check it.
